export enum SocketEvents {
  // User
  USER_LOGOUT = "user:logout",
  AUTH_ANNOUNCE_LOGIN = "auth:announce-login",
  AUTH_NEW_LOGIN = "auth:new-login",

  // Views
  VIEW_MESSAGE = "view:message",
  VIEWED_MESSAGE = "viewed:message",

  // Messages
  MESSAGE_SEND = "message:send",
  MESSAGE_SENT = "message:sent",
  MESSAGE_NEW = "message:new",
  MESSAGE_DELETE = "message:delete",
  MESSAGE_DELETED = "message:deleted",
  MESSAGE_EDIT = "message:edit",
  MESSAGE_EDITED = "message:edited",
  MESSAGE_TYPING = "message:typing",
  MESSAGE_FORWARD = "message:forward",
  MESSAGE_PIN = "message:pin",
  MESSAGE_PINNED = "message:pinned",
  MESSAGE_REACTION = "message:reaction",
  MESSAGE_REACTED = "message:reacted",

  // Spaces
  SPACE_JOIN = "space:join",
  SPACE_JOINED = "space:joined",
  SPACE_LEAVE = "space:leave",
  SPACE_LEFT = "space:left",
  SPACE_INFO_UPDATE = "space:info-update",
  SPACE_INFO_UPDATED = "space:info-updated",
  SPACE_CREATE_PRIVATE = "space:create-private",
  SPACE_CREATED_PRIVATE = "space:created-private",
  SPACE_READ = "space:read",
  SPACE_READABLE = "space:readable",
  SPACE_DELETE = "space:delete",
  SPACE_DELETED = "space:deleted",
  SPACE_CHANGE_WALLPAPER = "space:change-wallpaper",
  SPACE_WALLPAPER_CHANGED = "space:wallpaper-changed",
  SPACE_CLEAR_HISTORY = "space:clear-history",
  SPACE_HISTORY_CLEARED = "space:history-cleared",

  // Members
  MEMBER_ADD = "member:add",
  MEMBER_ADDED = "member:added",
  MEMBER_REMOVE = "member:remove",
  MEMBER_REMOVED = "member:removed",
  MEMBER_PROMOTE_ADMIN = "member:promote-admin",
  MEMBER_ADMIN_PROMOTED = "member:admin-promoted",
  MEMBER_DISMISS_ADMIN = "member:dismiss-admin",
  MEMBER_ADMIN_DISMISSED = "member:admin-dismissed",
  MEMBER_UPDATE_ADMIN_PERMISSIONS = "member:update-admin-permissions",
  MEMBER_ADMIN_PERMISSIONS_UPDATED = "member:admin-permissions-updated",
  MEMBER_UPDATE_PERMISSIONS = "member:update-permissions",
  MEMBER_PERMISSIONS_UPDATED = "member:permissions-updated",
  MEMBER_TRANSFER_OWNERSHIP = "member:transfer-ownership",
  MEMBER_OWNERSHIP_TRANSFERRED = "member:ownership-transferred",
  MEMBER_TOGGLE_BAN = "member:toggle-ban",

  // Presence
  PRESENCE_SUBSCRIBE = "presence:subscribe",
  PRESENCE_UNSUBSCRIBE = "presence:unsubscribe",
  PRESENCE_USER_ONLINE = "presence:user-online",
  PRESENCE_USER_OFFLINE = "presence:user-offline",
  PRESENCE_INACTIVE_SESSIONS = "sessions:inactive",
  PRESENCE_INACTIVATED_SESSIONS = "sessions:inactivated",
  PRESENCE_ONLINE_SESSIONS = "presence:online-sessions",

  // Calls
  CALL_START = "call:start",
  CALL_RINGING = "call:ringing",
  CALL_ACCEPT = "call:accept",
  CALL_ACCEPTED = "call:accepted",
  CALL_REJECT = "call:reject",
  CALL_REJECTED = "call:rejected",
  CALL_JOIN = "call:join",
  CALL_JOINED = "call:joined",
  CALL_LEAVE = "call:leave",
  CALL_LEFT = "call:left",
  CALL_END = "call:end",
  CALL_ENDED = "call:ended",
  CALL_SYNC = "call:sync",
  CALL_MESSAGE_SEND = "call:message-send",
  CALL_MESSAGE_SENT = "call:message-sent",
  CALL_MESSAGE_NEW = "call:message-new",
  CALL_MESSAGE_DELETE = "call:message-delete",
  CALL_MESSAGE_DELETED = "call:message-deleted",
  CALL_MESSAGE_EDIT = "call:message-edit",
  CALL_MESSAGE_EDITED = "call:message-edited",
  CALL_MESSAGE_TYPING = "call:message-typing",
  CALL_MESSAGE_FORWARD = "call:message-forward",
  CALL_MESSAGE_PIN = "call:message-pin",
  CALL_MESSAGE_PINNED = "call:message-pinned",
  CALL_MESSAGE_REACTION = "call:message-reaction",
  CALL_MESSAGE_REACTED = "call:message-reacted",
  CALL_TOGGLE_MUTE = "call:toggle-mute",
  CALL_TOGGLE_RAISE_HAND = "call:toggle-raise-hand",
  CALL_PARTICIPANT_UPDATED = "call:participant-updated",
  CALL_UPDATE_SETTINGS = "call:update-settings",
  CALL_SETTINGS_UPDATED = "call:settings-updated",

  // Webrtc
  WEBRTC_OFFER = "webrtc:offer",
  WEBRTC_ANSWER = "webrtc:answer",
  WEBRTC_ICE_CANDIDATE = "webrtc:ice-candidate",
  SCREEN_SHARE_STARTED = "call:screen-share-started",
  SCREEN_SHARE_STOPPED = "call:screen-share-stopped",

  // Banned
  BAN_TOGGLE = "ban:toggle",
  BAN_TOGGLED = "ban:toggled",
}
