/**
 * Translation keys for the messages the business rules throw (M1). The rules
 * keep plain English messages (also used in logs and tests); the UI looks the
 * message up here and shows it in the user's language. The server returns the
 * same keys as error codes.
 */
export const ERROR_KEYS: Record<string, string> = {
  "Choose a project": "err_chooseAProject",
  "Choose a person or name the role to staff": "err_chooseAPersonOrName",
  "The end date can't be before the start date": "err_theEndDateCanTBe",
  "Hours per week must be between 1 and 80": "err_hoursPerWeekMustBe",
  "Booking not found": "err_bookingNotFound",
  "Give the deal a name": "err_giveTheDealAName",
  "The amount can't be negative": "err_amountCantBeNegative",
  "Set the expected close date": "err_setExpectedCloseDate",
  "The chance of winning must be between 0 and 100%": "err_chanceBetween0And100",
  "Say why the deal was lost": "err_sayWhyDealLost",
  "Deal not found": "err_dealNotFound",
  "This phase is not part of the project": "err_phaseNotInProject",
  "Your console role does not allow this": "err_consoleForbidden",
  "Enter a name and a valid e-mail": "err_staffNameEmail",
  "This e-mail is already in the team": "err_staffDuplicate",
  "This invitation no longer exists": "err_inviteGone",
  "This invitation has expired": "err_inviteExpired",
  "This team member no longer exists": "err_staffGone",
  "The team must keep at least one platform owner": "err_lastOwner",
  "You cannot remove yourself": "err_removeSelf",
  "This session no longer exists": "err_sessionGone",
  "This session has already ended": "err_sessionEnded",
  "This status change is not allowed": "err_transition",
  "This customer no longer exists": "err_customerGone",
  "Enter the company, the administrator and a valid e-mail": "err_trialFields",
  "The ICE has 15 digits": "err_ice15",
  "This company or administrator is already a customer": "err_customerDuplicate",
  "Only a trial can be extended": "err_trialOnly",
  "This trial was already extended once": "err_trialExtended",
  "Lift the suspension instead": "err_liftInstead",
  "Give the reason for the suspension": "err_suspendReason",
  "The end date must be in the future": "err_untilFuture",
  "This customer is not suspended": "err_notSuspended",
  "A cancellation is already planned": "err_cancelPlanned",
  "No cancellation is planned": "err_noCancel",
  "Write the note first": "err_noteEmpty",
  "This person is already suspended": "err_userSuspended",
  "The company would have no administrator; suspend the company instead": "err_lastCompanyAdmin",
  "This suspension has already been lifted": "err_suspensionLifted",
  "Enter a price above zero": "err_priceZero",
  "The new price starts today or later": "err_priceDate",
  "A price already starts on that day": "err_priceSameDay",
  "This customer already has a subscription": "err_subExists",
  "This customer has no subscription yet": "err_noSub",
  "Enter the amount and the bank reference": "err_transferFields",
  "This transfer is no longer waiting": "err_transferGone",
  "The transfer is larger than what the invoice still owes": "err_transferTooBig",
  "This invoice no longer exists": "err_invoiceGone",
  "Give the reason for the credit note": "err_creditReason",
  "The credit note cannot exceed what is left on the invoice": "err_creditTooBig",
  "Only money received can be refunded": "err_refundTooBig",
  "This refund is not waiting for approval": "err_refundNotWaiting",
  "Another team member must approve this refund": "err_refundSecondPerson",
  "This support request no longer exists": "err_srGone",
  "This support session no longer exists": "err_ssGone",
  "This workspace is not linked to a Nexora customer": "err_wsNoCustomer",
  "Describe the problem in a few words": "err_srDescribe",
  "Write the message first": "err_msgEmpty",
  "Explain why you need access": "err_ssReason",
  "A session lasts between 15 minutes and 24 hours": "err_ssDuration",
  "You already have an open session request for this customer": "err_ssOpen",
  "This access request was already answered": "err_ssAnswered",
  "This session does not wait for an owner": "err_ssNoOwner",
  "Another platform owner must approve your own write session": "err_ssOwnSelf",
  "This incident no longer exists": "err_incGone",
  "Give the incident a title": "err_incTitle",
  "Choose at least one affected service": "err_incServices",
  "This incident is already resolved": "err_incResolved",
  "Resolve the incident with its resolution": "err_incUseResolve",
  "Write the update first": "err_incUpdateEmpty",
  "Write the message customers will read": "err_incNotice",
  "Describe how the incident was resolved": "err_incResolution",
  "A severity 1 or 2 incident needs a post-mortem": "err_incPostmortem",
  "Give the maintenance a title": "err_mntTitle",
  "A maintenance is announced at least 48 hours ahead": "err_mntLead",
  "The end must be after the start": "err_mntEnd",
  "This maintenance is already finished": "err_mntDone",
  "Choose from 1 to 5 stars": "err_chooseStars",
  "Choose a score from 0 to 10": "err_chooseNpsScore",
  "This survey was already answered": "err_surveyAlreadyAnswered",
  "Describe the change": "err_describeTheChange",
  "Enter the price and hours of the change": "err_enterChangePriceHours",
  "A change must change the price or the hours": "err_changeMustChangeSomething",
  "Change order not found": "err_changeOrderNotFound",
  "A decided change order can't be changed": "err_decidedChangeLocked",
  "Send the change to the client first": "err_sendChangeFirst",
  "Say why the client declined": "err_sayWhyClientDeclined",
  "Only a draft change order can be deleted": "err_onlyDraftChangeDeleted",
  "Choose a supplier": "err_chooseASupplier",
  "Enter the supplier's bill number": "err_enterTheSupplierSBill",
  "The due date can't be before the bill date": "err_theDueDateCanTBe",
  "VAT rates are between 0 and 100%": "err_vatRatesAreBetween0",
  "This supplier's bill number is already recorded": "err_thisSupplierSBillNumber",
  "Bill not found": "err_billNotFound",
  "Approved bills can't be changed": "err_approvedBillsCanTBe",
  "Only bills waiting for approval can be reviewed": "err_onlyBillsWaitingForApproval",
  "Approve the bill before paying it": "err_approveTheBillBeforePaying",
  "The payment is more than what is left to pay": "err_thePaymentIsMoreThan",
  "Approved bills can't be deleted": "err_approvedBillsCanTBe2",
  "This supplier has bills, so it can only be archived": "err_thisSupplierHasBillsSo",
  "Enter the supplier's name": "err_enterTheSupplierSName",
  "Payment terms must be between 0 and 365 days": "err_paymentTermsMustBeBetween",
  "A Moroccan RIB has 24 digits": "err_aMoroccanRibHas24",
  "Another supplier already uses this ICE": "err_anotherSupplierAlreadyUsesThis",
  "A supplier with this name already exists": "err_aSupplierWithThisName",
  "Supplier not found": "err_supplierNotFound",
  "Account numbers have 4 to 8 digits": "err_accountNumbersHave4To",
  "The VAT must be less than the amount": "err_theVatMustBeLess",
  "This invoice was sent to the DGI; issue a credit note instead": "err_thisInvoiceWasSentTo",
  "Issue the invoice before sending it to the DGI": "err_issueTheInvoiceBeforeSending",
  "E-invoicing applies to issued invoices of Moroccan companies": "err_eInvoicingAppliesToIssued",
  "This invoice was already sent to the DGI": "err_thisInvoiceWasAlreadySent",
  "Add the client's ICE: invoices to companies in Morocco must show it": "err_addTheClientSIceInvoices",
  "Add your company's ICE in Settings before issuing invoices": "err_addYourCompanySIceIn",
  "Add your company's IF (tax ID) in Settings before issuing invoices": "err_addYourCompanySIfTax",
  "The CNSS number must have 7 digits": "err_theCnssNumberMustHave",
  "The IF (tax ID) must have 6 to 8 digits": "err_theIfTaxIdMust",
  "The patente number must have 8 digits": "err_thePatenteNumberMustHave",
  "A completed review can't be cancelled": "err_aCompletedReviewCanTBe",
  "A credit note can't be credited": "err_aCreditNoteCanTBe",
  "A department with this name already exists": "err_aDepartmentWithThisNameAlready",
  "A fixed-term, freelance or internship contract needs an end date": "err_aFixedTermFreelanceOrInternship",
  "A half day must start and end on the same day": "err_aHalfDayMustStartAnd",
  "A task can only wait for tasks of the same project": "err_aTaskCanOnlyWaitFor",
  "A template with this name already exists": "err_aTemplateWithThisNameAlready",
  "Accept the quote before creating its project": "err_acceptTheQuoteBeforeCreatingIts",
  "Access not found": "err_accessNotFound",
  "Add a comment for the employee": "err_addACommentForTheEmployee",
  "Add a valid email to the employee first": "err_addAValidEmailToThe",
  "Add at least one line first": "err_addAtLeastOneLineFirst",
  "All seats of your plan are used; upgrade or disable an account first": "err_allSeatsOfYourPlanAre",
  "Amounts can't be negative": "err_amountsCanTBeNegative",
  "An employee can't be their own manager": "err_anEmployeeCanTBeTheir",
  "An employee with this email already exists": "err_anEmployeeWithThisEmailAlready",
  "Another contact already uses this email in the portal": "err_anotherContactAlreadyUsesThisEmail",
  "Another project already uses this code": "err_anotherProjectAlreadyUsesThisCode",
  "Approved expenses can't be deleted": "err_approvedExpensesCanTBeDeleted",
  "Archived clients can't use the portal": "err_archivedClientsCanTUseThe",
  "Carry-over must be between 0 and the yearly days": "err_carryOverMustBeBetween0",
  "Choose a client": "err_chooseAClient",
  "Choose at least one person": "err_chooseAtLeastOnePerson",
  "Choose the contract type": "err_chooseTheContractType",
  "Client not found": "err_clientNotFound",
  "Comments are limited to 5,000 characters": "err_commentsAreLimitedTo5000",
  "Contact not found": "err_contactNotFound",
  "Credit notes don't take payments": "err_creditNotesDonTTakePayments",
  "Describe the expense": "err_describeTheExpense",
  "Describe the project in a few words": "err_describeTheProjectInAFew",
  "Document not found": "err_documentNotFound",
  "Each holiday needs a date and a name": "err_eachHolidayNeedsADateAnd",
  "Each line needs a description, a quantity and a price": "err_eachLineNeedsADescriptionA",
  "Each rate card line needs a person or a job title, and a rate": "err_eachRateCardLineNeedsA",
  "Employee not found": "err_employeeNotFound",
  "Enter a department name": "err_enterADepartmentName",
  "Enter a valid billing email": "err_enterAValidBillingEmail",
  "Enter an amount above zero": "err_enterAnAmountAboveZero",
  "Enter the company's legal name": "err_enterTheCompanySLegalName",
  "Enter the deposit amount": "err_enterTheDepositAmount",
  "Enter the milestone amount": "err_enterTheMilestoneAmount",
  "Every custom field needs a name": "err_everyCustomFieldNeedsAName",
  "Every line needs a description": "err_everyLineNeedsADescription",
  "Every overhead line needs a name": "err_everyOverheadLineNeedsAName",
  "Expense not found": "err_expenseNotFound",
  "Expenses can't be in the future": "err_expensesCanTBeInThe",
  "Give a reason so the employee knows what to fix": "err_giveAReasonSoTheEmployee",
  "Give a reason when declining": "err_giveAReasonWhenDeclining",
  "Give a reason when rejecting": "err_giveAReasonWhenRejecting",
  "Give the contract a title": "err_giveTheContractATitle",
  "Give the contract start date": "err_giveTheContractStartDate",
  "Give the document a title": "err_giveTheDocumentATitle",
  "Give the project a code": "err_giveTheProjectACode",
  "Give the reason the client declined": "err_giveTheReasonTheClientDeclined",
  "Give the report a name": "err_giveTheReportAName",
  "Give the schedule a name": "err_giveTheScheduleAName",
  "Give the template a name": "err_giveTheTemplateAName",
  "Hours must be zero or more": "err_hoursMustBeZeroOrMore",
  "Invoice not found": "err_invoiceNotFound",
  "Invoiced hours can't be reopened; issue a credit note instead": "err_invoicedHoursCanTBeReopened",
  "Keep at least one administrator who can sign in": "err_keepAtLeastOneAdministratorWho",
  "Keep at least one expense category": "err_keepAtLeastOneExpenseCategory",
  "Keep at least one leave type": "err_keepAtLeastOneLeaveType",
  "Labels need a name": "err_labelsNeedAName",
  "Leave request not found": "err_leaveRequestNotFound",
  "Leave that has started or ended can't be cancelled": "err_leaveThatHasStartedOrEnded",
  "Lines billed from hours or expenses can't change; remove the invoice to re-bill them": "err_linesBilledFromHoursOrExpenses",
  "Milestone not found": "err_milestoneNotFound",
  "More than 24 hours in one day": "err_moreThan24HoursInOne",
  "Move its people to another department first": "err_moveItsPeopleToAnotherDepartment",
  "Name the review cycle, e.g. H2 2026": "err_nameTheReviewCycleEG",
  "No hours to submit": "err_noHoursToSubmit",
  "No timer is running": "err_noTimerIsRunning",
  "Nothing is owed on this invoice": "err_nothingIsOwedOnThisInvoice",
  "Nothing was logged last week": "err_nothingWasLoggedLastWeek",
  "Only a sent quote can be accepted": "err_onlyASentQuoteCanBe",
  "Only a sent quote can be declined": "err_onlyASentQuoteCanBe2",
  "Only an accepted quote can be invoiced": "err_onlyAnAcceptedQuoteCanBe",
  "Only an admin can cancel a review": "err_onlyAnAdminCanCancelA",
  "Only approved expenses can be reimbursed": "err_onlyApprovedExpensesCanBeReimbursed",
  "Only approved hours can be reopened": "err_onlyApprovedHoursCanBeReopened",
  "Only draft invoices can be edited": "err_onlyDraftInvoicesCanBeEdited",
  "Only draft quotes can be deleted; sent quotes are kept for the record": "err_onlyDraftQuotesCanBeDeleted",
  "Only draft quotes can be edited; duplicate it to make a new version": "err_onlyDraftQuotesCanBeEdited",
  "Only drafts can be deleted; cancel an issued invoice instead": "err_onlyDraftsCanBeDeletedCancel",
  "Only drafts can be issued": "err_onlyDraftsCanBeIssued",
  "Only fixed-price projects with a price can be billed this way": "err_onlyFixedPriceProjectsWithA",
  "Only issued invoices can be credited": "err_onlyIssuedInvoicesCanBeCredited",
  "Only pending requests can be decided": "err_onlyPendingRequestsCanBeDecided",
  "Only people on the project team can be assigned": "err_onlyPeopleOnTheProjectTeam",
  "Only submitted expenses can be reviewed": "err_onlySubmittedExpensesCanBeReviewed",
  "Only submitted hours can be reviewed": "err_onlySubmittedHoursCanBeReviewed",
  "Only the employee can acknowledge their review": "err_onlyTheEmployeeCanAcknowledgeTheir",
  "Only the employee can fill in the self-assessment": "err_onlyTheEmployeeCanFillIn",
  "Only the person who saved this report can delete it": "err_onlyThePersonWhoSavedThis",
  "Only the project team can add expenses to it": "err_onlyTheProjectTeamCanAdd",
  "Only the project team can log time on it": "err_onlyTheProjectTeamCanLog",
  "Only the reviewer can complete this review": "err_onlyTheReviewerCanCompleteThis",
  "Payments can only be recorded on issued invoices": "err_paymentsCanOnlyBeRecordedOn",
  "Pick a base currency": "err_pickABaseCurrency",
  "Pick a client": "err_pickAClient",
  "Pick a date": "err_pickADate",
  "Pick a project of this client": "err_pickAProjectOfThisClient",
  "Pick a share between 1 and 100%": "err_pickAShareBetween1And",
  "Pick a start date": "err_pickAStartDate",
  "Pick at least one line to credit": "err_pickAtLeastOneLineTo",
  "Pick at least one working day": "err_pickAtLeastOneWorkingDay",
  "Pick the date the rates take effect": "err_pickTheDateTheRatesTake",
  "Pick the first month of the fiscal year": "err_pickTheFirstMonthOfThe",
  "Pick the month to bill": "err_pickTheMonthToBill",
  "Pick the payment date": "err_pickThePaymentDate",
  "Project not found": "err_projectNotFound",
  "Quantities must be above zero and prices not negative": "err_quantitiesMustBeAboveZeroAnd",
  "Quote not found": "err_quoteNotFound",
  "Rate every criterion from 1 to 5": "err_rateEveryCriterionFrom1To",
  "Rate targets must be 200% or less": "err_rateTargetsMustBe200Or",
  "Rates can't be negative": "err_ratesCanTBeNegative",
  "Rates can't start before the hire date": "err_ratesCanTStartBeforeThe",
  "Reminder days must be whole numbers that increase, from 1 to 365": "err_reminderDaysMustBeWholeNumbers",
  "Review not found": "err_reviewNotFound",
  "Say why the hours are reopened": "err_sayWhyTheHoursAreReopened",
  "Say why the status differs from the automatic one": "err_sayWhyTheStatusDiffersFrom",
  "Schedule not found": "err_scheduleNotFound",
  "Select at least one block of approved hours": "err_selectAtLeastOneBlockOf",
  "Some expenses are no longer available to invoice": "err_someExpensesAreNoLongerAvailable",
  "Some hours are no longer available to invoice": "err_someHoursAreNoLongerAvailable",
  "Some of these lines were already credited": "err_someOfTheseLinesWereAlready",
  "Submitted or approved hours can't be changed": "err_submittedOrApprovedHoursCanT",
  "Targets can't be negative": "err_targetsCanTBeNegative",
  "Task not found": "err_taskNotFound",
  "Tax must be between 0 and 100%": "err_taxMustBeBetween0And",
  "Team member not found": "err_teamMemberNotFound",
  "Tell the team what should change": "err_tellTheTeamWhatShouldChange",
  "Template not found": "err_templateNotFound",
  "That milestone belongs to another project": "err_thatMilestoneBelongsToAnotherProject",
  "The ICE must have exactly 15 digits": "err_theIceMustHaveExactly15",
  "The brand colour must look like #2563eb": "err_theBrandColourMustLookLike",
  "The delivery date can't be before the quote date": "err_theDeliveryDateCanTBe",
  "The discount must be between 0 and 100%": "err_theDiscountMustBeBetween0",
  "The due date can't be before the issue date": "err_theDueDateCanTBe",
  "The due date can't be before the start date": "err_theDueDateCanTBe2",
  "The end date is before the start date": "err_theEndDateIsBeforeThe",
  "The exchange rate must be above zero": "err_theExchangeRateMustBeAbove",
  "The expiry date can't be before the start date": "err_theExpiryDateCanTBe",
  "The invoice number format must contain {SEQ}": "err_theInvoiceNumberFormatMustContain",
  "The last day can't be before the first day": "err_theLastDayCanTBe",
  "The logo must be a PNG or JPEG under 300 KB": "err_theLogoMustBeAPng",
  "The period must start before it ends": "err_thePeriodMustStartBeforeIt",
  "The quote number format must contain {SEQ}": "err_theQuoteNumberFormatMustContain",
  "The rate card has the same person or job title twice": "err_theRateCardHasTheSame",
  "The second approval must come from someone else": "err_theSecondApprovalMustComeFrom",
  "The smallest step is 15 minutes (0.25 h)": "err_theSmallestStepIs15Minutes",
  "The start date is after the due date": "err_theStartDateIsAfterThe",
  "The validity date can't be before the quote date": "err_theValidityDateCanTBe",
  "The value can't be negative": "err_theValueCanTBeNegative",
  "These dependencies would make tasks wait for each other in a loop": "err_theseDependenciesWouldMakeTasksWait",
  "This category is turned off in the workspace settings": "err_thisCategoryIsTurnedOffIn",
  "This client has invoices, so it can only be archived": "err_thisClientHasInvoicesSoIt",
  "This employee already has access": "err_thisEmployeeAlreadyHasAccess",
  "This employee has left the company": "err_thisEmployeeHasLeftTheCompany",
  "This employee has no account": "err_thisEmployeeHasNoAccount",
  "This invoice can't be sent": "err_thisInvoiceCanTBeSent",
  "This invoice can't move to that status": "err_thisInvoiceCanTMoveTo",
  "This invoice has payments; issue a credit note instead": "err_thisInvoiceHasPaymentsIssueA",
  "This leave type is turned off in the workspace settings": "err_thisLeaveTypeIsTurnedOff",
  "This milestone isn't waiting for your approval": "err_thisMilestoneIsnTWaitingFor",
  "This month of the retainer is already invoiced": "err_thisMonthOfTheRetainerIs",
  "This overlaps another leave request": "err_thisOverlapsAnotherLeaveRequest",
  "This person has logged time, expenses or reviews. Set them to Former employee instead, so their history stays.": "err_thisPersonHasLoggedTimeExpenses",
  "This project code is already used": "err_thisProjectCodeIsAlreadyUsed",
  "This project is already closed": "err_thisProjectIsAlreadyClosed",
  "This project is closed, so it no longer accepts hours": "err_thisProjectIsClosedSoIt",
  "This project isn't closed": "err_thisProjectIsnTClosed",
  "This project isn't on a retainer": "err_thisProjectIsnTOnA",
  "This quote already has a project": "err_thisQuoteAlreadyHasAProject",
  "This quote has already been answered": "err_thisQuoteHasAlreadyBeenAnswered",
  "This quote has already been invoiced": "err_thisQuoteHasAlreadyBeenInvoiced",
  "This reminder was already sent": "err_thisReminderWasAlreadySent",
  "This schedule has ended": "err_thisScheduleHasEnded",
  "This schedule is paused": "err_thisScheduleIsPaused",
  "This week already has those rows filled in": "err_thisWeekAlreadyHasThoseRows",
  "This would bill more than the project price": "err_thisWouldBillMoreThanThe",
  "Two holidays are on the same date": "err_twoHolidaysAreOnTheSame",
  "Two labels have the same name": "err_twoLabelsHaveTheSameName",
  "VAT must be between 0 and 100%": "err_vatMustBeBetween0And",
  "Withholding must be between 0 and 100%": "err_withholdingMustBeBetween0And",
  "Write a comment first": "err_writeACommentFirst",
  "Write something first": "err_writeSomethingFirst",
  "Yearly days must be between 0 and 366": "err_yearlyDaysMustBeBetween0",
  "You already have a report with this name": "err_youAlreadyHaveAReportWith",
  "You can't approve your own request": "err_youCanTApproveYourOwn",
  "Storage is full; this change was not saved": "err_storageFull",
}

/** Messages with values: each captured group becomes the value named at the same position in `names`. */
export const ERROR_PATTERNS: { pattern: RegExp; key: string; names: string[] }[] = [
  { pattern: /^Free (\d+) seats before this downgrade$/, key: "err_freeSeats", names: ["count"] },
  { pattern: /^Attach a receipt for expenses above (.+)$/, key: "err_receiptAbove", names: ["amount"] },
  { pattern: /^The period up to (.+) is locked$/, key: "err_periodLocked", names: ["date"] },
  { pattern: /^Enter the exchange rate from (\S+) to (\S+)$/, key: "err_exchangeRate", names: ["from", "to"] },
  { pattern: /^Only ([\d.,]+) is left to pay$/, key: "err_leftToPay", names: ["amount"] },
  { pattern: /^"(.+)" needs at least two choices$/, key: "err_fieldTwoChoices", names: ["name"] },
  { pattern: /^Two fields are named "(.+)"$/, key: "err_fieldDuplicate", names: ["name"] },
  { pattern: /^This plan allows (\d+) users and (\d+) have access; remove access first$/, key: "err_seatsUsed", names: ["seats", "used"] },
  { pattern: /^Only ([\d.]+) day\(s\) left in (\d+); this request needs ([\d.]+)$/, key: "err_leaveBalance", names: ["left", "year", "need"] },
]
