/**
 * @fileoverview 1-Year Historical Demo Dataset for Content Reports and System Issues.
 * Spans October 2025 to September 2026 for high-fidelity enterprise client demos.
 */

import {
  ContentReport,
  ContentReportStats,
  ReportStatus,
  ReportType,
  ReportReason,
  SystemIssue,
  SystemIssueStats,
  IssueStatus,
  IssuePriority,
  IssueCategory,
} from "@/types/reports"

export const INITIAL_DEMO_CONTENT_REPORTS: ContentReport[] = [
  {
    id: "rep-2026-024",
    reporterId: "usr-demo-2",
    reporterName: "Sarah Chen",
    reporterAvatar: "/avatars/sarah-chen.jpg",
    targetId: "usr-demo-7",
    targetName: "Liam O'Connor",
    targetAvatar: "/avatars/liam-oconnor.jpg",
    targetType: ReportType.USER,
    reason: ReportReason.IMPERSONATION,
    description: "Suspicious profile clone attempting to solicit team workspace admin tokens via direct message.",
    status: ReportStatus.PENDING,
    createdAt: "2026-09-18T14:32:00Z",
    updatedAt: "2026-09-18T14:32:00Z",
  },
  {
    id: "rep-2026-023",
    reporterId: "usr-demo-1",
    reporterName: "Alex Morgan",
    reporterAvatar: "/avatars/alex-morgan.jpg",
    targetId: "proj-101",
    targetName: "Quantum AI Engine",
    targetType: ReportType.PROJECT,
    reason: ReportReason.COPYRIGHT,
    description: "Public project repository contains proprietary neural architecture headers licensed under restrictive NDA.",
    status: ReportStatus.REVIEWING,
    createdAt: "2026-09-08T11:15:00Z",
    updatedAt: "2026-09-09T09:40:00Z",
    resolutionNotes: "Legal compliance team is auditing third-party dependencies and licensing disclaimers.",
  },
  {
    id: "rep-2026-022",
    reporterId: "usr-demo-4",
    reporterName: "Elena Rostova",
    reporterAvatar: "/avatars/elena-rostova.jpg",
    targetId: "file-904",
    targetName: "Unverified-Payment-Gateway-Keys.env",
    targetType: ReportType.FILE,
    reason: ReportReason.FRAUD,
    description: "Shared asset folder contains unencrypted test credentials exposing Stripe test sandbox hooks.",
    status: ReportStatus.PENDING,
    createdAt: "2026-08-25T16:20:00Z",
    updatedAt: "2026-08-25T16:20:00Z",
  },
  {
    id: "rep-2026-021",
    reporterId: "usr-demo-6",
    reporterName: "Rachel Thorne",
    reporterAvatar: "/avatars/rachel-thorne.jpg",
    targetId: "sub-501",
    targetName: "Enterprise Tier - FinTech Global",
    targetType: ReportType.SUBSCRIPTION,
    reason: ReportReason.FRAUD,
    description: "Anomalous multi-region IP activity triggering simultaneous seat activations in unapproved geographies.",
    status: ReportStatus.REVIEWING,
    createdAt: "2026-08-14T08:50:00Z",
    updatedAt: "2026-08-15T12:10:00Z",
    resolutionNotes: "Flagged to Security Operations Center; geo-fencing policy enforced.",
  },
  {
    id: "rep-2026-020",
    reporterId: "usr-demo-3",
    reporterName: "Marcus Vance",
    reporterAvatar: "/avatars/marcus-vance.jpg",
    targetId: "tx-984210",
    targetName: "TX-984210",
    targetType: ReportType.TRANSACTION,
    reason: ReportReason.OTHER,
    description: "Duplicate authorization request received for high-volume invoice reconciliation.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2026-07-29T17:00:00Z",
    resolvedBy: "Alex Morgan",
    resolutionNotes: "Reconciliation verified. Duplicate hold released through banking gateway.",
    actionTaken: "Hold canceled and refunded.",
    createdAt: "2026-07-28T10:00:00Z",
    updatedAt: "2026-07-29T17:00:00Z",
  },
  {
    id: "rep-2026-019",
    reporterId: "usr-demo-5",
    reporterName: "David Kim",
    reporterAvatar: "/avatars/david-kim.jpg",
    targetId: "inv-2026-044",
    targetName: "INV-2026-044",
    targetType: ReportType.INVOICE,
    reason: ReportReason.OTHER,
    description: "VAT identification number mismatch on generated cross-border invoice document.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2026-07-16T14:15:00Z",
    resolvedBy: "Rachel Thorne",
    resolutionNotes: "Updated corporate tax ID with EU VIES registry and re-issued invoice PDF.",
    actionTaken: "Invoice corrected and dispatched.",
    createdAt: "2026-07-15T09:30:00Z",
    updatedAt: "2026-07-16T14:15:00Z",
  },
  {
    id: "rep-2026-018",
    reporterId: "usr-demo-8",
    reporterName: "Priya Patel",
    reporterAvatar: "/avatars/priya-patel.jpg",
    targetId: "usr-demo-5",
    targetName: "David Kim",
    targetAvatar: "/avatars/david-kim.jpg",
    targetType: ReportType.USER,
    reason: ReportReason.SPAM,
    description: "Automated test script flooded team channel with notification pings during off-hours.",
    status: ReportStatus.DISMISSED,
    resolvedAt: "2026-06-22T11:00:00Z",
    resolvedBy: "Alex Morgan",
    resolutionNotes: "Legitimate staging webhook integration test. Rate limiter configured.",
    actionTaken: "Report dismissed without sanction.",
    createdAt: "2026-06-21T22:45:00Z",
    updatedAt: "2026-06-22T11:00:00Z",
  },
  {
    id: "rep-2026-017",
    reporterId: "usr-demo-2",
    reporterName: "Sarah Chen",
    reporterAvatar: "/avatars/sarah-chen.jpg",
    targetId: "proj-103",
    targetName: "FinTech Realtime Clearing",
    targetType: ReportType.PROJECT,
    reason: ReportReason.INAPPROPRIATE_CONTENT,
    description: "Debug log artifacts committed to repo contain unredacted end-user test phone numbers.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2026-06-12T15:30:00Z",
    resolvedBy: "Rachel Thorne",
    resolutionNotes: "Repository git history scrubbed with BFG repo-cleaner and synthetic dataset loaded.",
    actionTaken: "Sensitive data sanitized.",
    createdAt: "2026-06-11T13:10:00Z",
    updatedAt: "2026-06-12T15:30:00Z",
  },
  {
    id: "rep-2026-016",
    reporterId: "usr-demo-4",
    reporterName: "Elena Rostova",
    reporterAvatar: "/avatars/elena-rostova.jpg",
    targetId: "file-902",
    targetName: "Competitor-Architecture-Teardown.pdf",
    targetType: ReportType.FILE,
    reason: ReportReason.COPYRIGHT,
    description: "Document includes confidential schematic diagrams from external vendor without trademark attribution.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2026-05-24T18:00:00Z",
    resolvedBy: "Alex Morgan",
    resolutionNotes: "Replaced diagrams with high-level conceptual illustrations.",
    actionTaken: "File version updated.",
    createdAt: "2026-05-23T10:15:00Z",
    updatedAt: "2026-05-24T18:00:00Z",
  },
  {
    id: "rep-2026-015",
    reporterId: "usr-demo-1",
    reporterName: "Alex Morgan",
    reporterAvatar: "/avatars/alex-morgan.jpg",
    targetId: "sub-402",
    targetName: "Scale Tier - Apex Ventures",
    targetType: ReportType.SUBSCRIPTION,
    reason: ReportReason.OTHER,
    description: "Disputed credit card chargeback notification received from payment network.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2026-05-15T16:45:00Z",
    resolvedBy: "Alex Morgan",
    resolutionNotes: "Customer CFO clarified internal card renewal. Proof of service accepted by merchant bank.",
    actionTaken: "Chargeback reversed.",
    createdAt: "2026-05-10T14:20:00Z",
    updatedAt: "2026-05-15T16:45:00Z",
  },
  {
    id: "rep-2026-014",
    reporterId: "usr-demo-3",
    reporterName: "Marcus Vance",
    reporterAvatar: "/avatars/marcus-vance.jpg",
    targetId: "tx-984180",
    targetName: "TX-984180",
    targetType: ReportType.TRANSACTION,
    reason: ReportReason.FRAUD,
    description: "Multiple failed card velocity attempts preceding a single large transaction.",
    status: ReportStatus.DISMISSED,
    resolvedAt: "2026-04-19T13:10:00Z",
    resolvedBy: "Rachel Thorne",
    resolutionNotes: "Verified customer updated expiration date multiple times before succeeding.",
    actionTaken: "False positive cleared.",
    createdAt: "2026-04-18T19:00:00Z",
    updatedAt: "2026-04-19T13:10:00Z",
  },
  {
    id: "rep-2026-013",
    reporterId: "usr-demo-7",
    reporterName: "Liam O'Connor",
    reporterAvatar: "/avatars/liam-oconnor.jpg",
    targetId: "inv-2026-028",
    targetName: "INV-2026-028",
    targetType: ReportType.INVOICE,
    reason: ReportReason.OTHER,
    description: "Customer requested itemized breakdown of GPU inference metering hours.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2026-04-05T10:30:00Z",
    resolvedBy: "Alex Morgan",
    resolutionNotes: "Sent granular CSV export of GPU compute consumption logs.",
    actionTaken: "Itemized statement delivered.",
    createdAt: "2026-04-04T11:20:00Z",
    updatedAt: "2026-04-05T10:30:00Z",
  },
  {
    id: "rep-2026-012",
    reporterId: "usr-demo-6",
    reporterName: "Rachel Thorne",
    reporterAvatar: "/avatars/rachel-thorne.jpg",
    targetId: "usr-demo-3",
    targetName: "Marcus Vance",
    targetAvatar: "/avatars/marcus-vance.jpg",
    targetType: ReportType.USER,
    reason: ReportReason.HARASSMENT,
    description: "Heated discussion regarding production deployment schedule in general feedback thread.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2026-03-28T17:00:00Z",
    resolvedBy: "Rachel Thorne",
    resolutionNotes: "Mediation meeting held with team leads. Code of conduct reiterated.",
    actionTaken: "Internal resolution agreed.",
    createdAt: "2026-03-27T15:40:00Z",
    updatedAt: "2026-03-28T17:00:00Z",
  },
  {
    id: "rep-2026-011",
    reporterId: "usr-demo-5",
    reporterName: "David Kim",
    reporterAvatar: "/avatars/david-kim.jpg",
    targetId: "proj-105",
    targetName: "Enterprise SSO Portal",
    targetType: ReportType.PROJECT,
    reason: ReportReason.SPAM,
    description: "Automated bot created 50+ empty test workspaces with generic titles.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2026-03-14T09:20:00Z",
    resolvedBy: "Alex Morgan",
    resolutionNotes: "Purged empty test workspaces and added Turnstile captcha to project provisioning.",
    actionTaken: "Workspaces pruned and rate-limits tightened.",
    createdAt: "2026-03-13T23:05:00Z",
    updatedAt: "2026-03-14T09:20:00Z",
  },
  {
    id: "rep-2026-010",
    reporterId: "usr-demo-2",
    reporterName: "Sarah Chen",
    reporterAvatar: "/avatars/sarah-chen.jpg",
    targetId: "file-899",
    targetName: "ML-Dataset-Sample-v1.tar.gz",
    targetType: ReportType.FILE,
    reason: ReportReason.COPYRIGHT,
    description: "Public download link contains scraped dataset with ambiguous permissive license terms.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2026-02-20T12:00:00Z",
    resolvedBy: "Rachel Thorne",
    resolutionNotes: "Replaced with synthetic dataset generated in-house with full IP ownership.",
    actionTaken: "Clean asset substituted.",
    createdAt: "2026-02-18T14:10:00Z",
    updatedAt: "2026-02-20T12:00:00Z",
  },
  {
    id: "rep-2026-009",
    reporterId: "usr-demo-1",
    reporterName: "Alex Morgan",
    reporterAvatar: "/avatars/alex-morgan.jpg",
    targetId: "sub-301",
    targetName: "Starter Tier - Global Media",
    targetType: ReportType.SUBSCRIPTION,
    reason: ReportReason.FRAUD,
    description: "Trial account used prepaid virtual cards to repeatedly bypass compute quotas.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2026-02-05T16:00:00Z",
    resolvedBy: "Alex Morgan",
    resolutionNotes: "Blocked BIN number range for prepaid virtual issuers on free trial signups.",
    actionTaken: "Account suspended and BIN range blacklisted.",
    createdAt: "2026-02-04T18:30:00Z",
    updatedAt: "2026-02-05T16:00:00Z",
  },
  {
    id: "rep-2026-008",
    reporterId: "usr-demo-4",
    reporterName: "Elena Rostova",
    reporterAvatar: "/avatars/elena-rostova.jpg",
    targetId: "tx-984120",
    targetName: "TX-984120",
    targetType: ReportType.TRANSACTION,
    reason: ReportReason.OTHER,
    description: "SEPA transfer marked as received in ERP but webhook failed to trigger in Nexora.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2026-01-22T11:45:00Z",
    resolvedBy: "Rachel Thorne",
    resolutionNotes: "Manually reconciled banking ledger entry and fired synthetic payment webhook.",
    actionTaken: "Payment state synchronized.",
    createdAt: "2026-01-21T09:15:00Z",
    updatedAt: "2026-01-22T11:45:00Z",
  },
  {
    id: "rep-2026-007",
    reporterId: "usr-demo-6",
    reporterName: "Rachel Thorne",
    reporterAvatar: "/avatars/rachel-thorne.jpg",
    targetId: "inv-2026-005",
    targetName: "INV-2026-005",
    targetType: ReportType.INVOICE,
    reason: ReportReason.OTHER,
    description: "Tax exemption certificate submitted by client not reflected in final invoice total.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2026-01-10T14:20:00Z",
    resolvedBy: "Alex Morgan",
    resolutionNotes: "Validated 501(c)(3) certificate with IRS database and applied tax exemption waiver.",
    actionTaken: "Corrected invoice issued.",
    createdAt: "2026-01-08T16:00:00Z",
    updatedAt: "2026-01-10T14:20:00Z",
  },
  {
    id: "rep-2025-006",
    reporterId: "usr-demo-8",
    reporterName: "Priya Patel",
    reporterAvatar: "/avatars/priya-patel.jpg",
    targetId: "usr-demo-7",
    targetName: "Liam O'Connor",
    targetAvatar: "/avatars/liam-oconnor.jpg",
    targetType: ReportType.USER,
    reason: ReportReason.OTHER,
    description: "Repeated permission escalations requested without manager approval documentation.",
    status: ReportStatus.DISMISSED,
    resolvedAt: "2025-12-18T10:00:00Z",
    resolvedBy: "Rachel Thorne",
    resolutionNotes: "Formal promotion to engineering staff approved by director; role update legitimate.",
    actionTaken: "Dismissed with verified approval trail.",
    createdAt: "2025-12-17T11:20:00Z",
    updatedAt: "2025-12-18T10:00:00Z",
  },
  {
    id: "rep-2025-005",
    reporterId: "usr-demo-3",
    reporterName: "Marcus Vance",
    reporterAvatar: "/avatars/marcus-vance.jpg",
    targetId: "proj-099",
    targetName: "Legacy Billing Migration",
    targetType: ReportType.PROJECT,
    reason: ReportReason.OTHER,
    description: "Obsolete project remains listed in active directory causing user routing confusion.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2025-12-05T16:30:00Z",
    resolvedBy: "Alex Morgan",
    resolutionNotes: "Archived legacy project and redirected traffic to current v2 billing infrastructure.",
    actionTaken: "Project archived.",
    createdAt: "2025-12-04T14:00:00Z",
    updatedAt: "2025-12-05T16:30:00Z",
  },
  {
    id: "rep-2025-004",
    reporterId: "usr-demo-1",
    reporterName: "Alex Morgan",
    reporterAvatar: "/avatars/alex-morgan.jpg",
    targetId: "file-850",
    targetName: "Q4-Revenue-Projection-Final.xlsx",
    targetType: ReportType.FILE,
    reason: ReportReason.OTHER,
    description: "Public read permission incorrectly enabled for financial spreadsheet.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2025-11-20T11:15:00Z",
    resolvedBy: "Alex Morgan",
    resolutionNotes: "Restricted file access to executive finance group and rotated public share tokens.",
    actionTaken: "Permissions locked down.",
    createdAt: "2025-11-20T10:00:00Z",
    updatedAt: "2025-11-20T11:15:00Z",
  },
  {
    id: "rep-2025-003",
    reporterId: "usr-demo-2",
    reporterName: "Sarah Chen",
    reporterAvatar: "/avatars/sarah-chen.jpg",
    targetId: "sub-201",
    targetName: "Growth Tier - Nordic Scale",
    targetType: ReportType.SUBSCRIPTION,
    reason: ReportReason.OTHER,
    description: "Discrepancy in allocated storage limit after plan tier upgrade.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2025-11-08T15:20:00Z",
    resolvedBy: "Rachel Thorne",
    resolutionNotes: "Storage quota updated to 2TB and cache invalidated in S3 bucket coordinator.",
    actionTaken: "Quota provisioned.",
    createdAt: "2025-11-07T12:30:00Z",
    updatedAt: "2025-11-08T15:20:00Z",
  },
  {
    id: "rep-2025-002",
    reporterId: "usr-demo-5",
    reporterName: "David Kim",
    reporterAvatar: "/avatars/david-kim.jpg",
    targetId: "tx-984050",
    targetName: "TX-984050",
    targetType: ReportType.TRANSACTION,
    reason: ReportReason.OTHER,
    description: "Currency exchange rate applied differed from spot rate at time of checkout.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2025-10-25T14:00:00Z",
    resolvedBy: "Alex Morgan",
    resolutionNotes: "Adjusted for 0.4% conversion spread difference via credit balance credit.",
    actionTaken: "Credit applied to balance.",
    createdAt: "2025-10-24T18:10:00Z",
    updatedAt: "2025-10-25T14:00:00Z",
  },
  {
    id: "rep-2025-001",
    reporterId: "usr-demo-4",
    reporterName: "Elena Rostova",
    reporterAvatar: "/avatars/elena-rostova.jpg",
    targetId: "inv-2025-090",
    targetName: "INV-2025-090",
    targetType: ReportType.INVOICE,
    reason: ReportReason.OTHER,
    description: "Annual prepayment discount 20% omitted on upfront contract generation.",
    status: ReportStatus.RESOLVED,
    resolvedAt: "2025-10-12T16:30:00Z",
    resolvedBy: "Rachel Thorne",
    resolutionNotes: "Applied Enterprise Annual 20% discount coupon and regenerated receipt.",
    actionTaken: "Discount applied.",
    createdAt: "2025-10-11T13:45:00Z",
    updatedAt: "2025-10-12T16:30:00Z",
  },
]

export const INITIAL_DEMO_SYSTEM_ISSUES: SystemIssue[] = [
  {
    id: "iss-2026-024",
    title: "PostgreSQL read replica replication lag spike in us-east-2",
    description: "Replication lag reached 4200ms during quarterly financial batch export run, causing intermittent stale reads in analytics tables.",
    category: IssueCategory.DATABASE,
    priority: IssuePriority.HIGH,
    status: IssueStatus.IN_PROGRESS,
    assignedTo: "usr-demo-1",
    assignedToName: "Alex Morgan",
    assignedToAvatar: "/avatars/alex-morgan.jpg",
    reportedBy: "usr-demo-6",
    reportedByName: "Rachel Thorne",
    reportedByAvatar: "/avatars/rachel-thorne.jpg",
    createdAt: "2026-09-20T10:15:00Z",
    updatedAt: "2026-09-21T08:30:00Z",
  },
  {
    id: "iss-2026-023",
    title: "Stripe Webhook signature verification timeout during peak traffic",
    description: "Occasional 504 gateway timeout when verifying high concurrency payment webhook bursts over 150 req/sec.",
    category: IssueCategory.API,
    priority: IssuePriority.CRITICAL,
    status: IssueStatus.OPEN,
    assignedTo: "usr-demo-2",
    assignedToName: "Sarah Chen",
    assignedToAvatar: "/avatars/sarah-chen.jpg",
    reportedBy: "usr-demo-4",
    reportedByName: "Elena Rostova",
    reportedByAvatar: "/avatars/elena-rostova.jpg",
    createdAt: "2026-09-17T14:40:00Z",
    updatedAt: "2026-09-17T14:40:00Z",
  },
  {
    id: "iss-2026-022",
    title: "Dark mode high contrast border clipping on Safari 18",
    description: "Subtle 1px border clipping occurs around modal dialog close icons when viewed on macOS Sequoia Safari 18.",
    category: IssueCategory.UI_UX,
    priority: IssuePriority.LOW,
    status: IssueStatus.OPEN,
    assignedTo: "usr-demo-7",
    assignedToName: "Liam O'Connor",
    assignedToAvatar: "/avatars/liam-oconnor.jpg",
    reportedBy: "usr-demo-3",
    reportedByName: "Marcus Vance",
    reportedByAvatar: "/avatars/marcus-vance.jpg",
    createdAt: "2026-09-10T11:20:00Z",
    updatedAt: "2026-09-10T11:20:00Z",
  },
  {
    id: "iss-2026-021",
    title: "Memory leak in real-time WebSocket subscriber connection pool",
    description: "Node.js cluster worker RSS footprint increments 15MB/hour due to retained abandoned TCP socket references.",
    category: IssueCategory.PERFORMANCE,
    priority: IssuePriority.HIGH,
    status: IssueStatus.IN_PROGRESS,
    assignedTo: "usr-demo-6",
    assignedToName: "Rachel Thorne",
    assignedToAvatar: "/avatars/rachel-thorne.jpg",
    reportedBy: "usr-demo-1",
    reportedByName: "Alex Morgan",
    reportedByAvatar: "/avatars/alex-morgan.jpg",
    createdAt: "2026-08-28T09:00:00Z",
    updatedAt: "2026-08-29T15:20:00Z",
  },
  {
    id: "iss-2026-020",
    title: "Zero-day vulnerability patch in bundled upstream OpenSSL library",
    description: "Security advisory CVE-2026-4410 requires base Alpine container rebuild and TLS cipher reordering.",
    category: IssueCategory.SECURITY,
    priority: IssuePriority.CRITICAL,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-1",
    assignedToName: "Alex Morgan",
    assignedToAvatar: "/avatars/alex-morgan.jpg",
    reportedBy: "usr-demo-6",
    reportedByName: "Rachel Thorne",
    reportedByAvatar: "/avatars/rachel-thorne.jpg",
    resolvedAt: "2026-08-16T18:00:00Z",
    resolutionNotes: "Rebuilt Docker production images with patched OpenSSL 3.3.2. Automated container scan passed.",
    createdAt: "2026-08-15T08:30:00Z",
    updatedAt: "2026-08-16T18:00:00Z",
  },
  {
    id: "iss-2026-019",
    title: "Kubernetes ingress autoscaler thrashing under flash crowd surge",
    description: "HPA target CPU threshold of 60% caused pod count oscillation between 8 and 32 pods within 10-minute window.",
    category: IssueCategory.DEPLOYMENT,
    priority: IssuePriority.HIGH,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-6",
    assignedToName: "Rachel Thorne",
    assignedToAvatar: "/avatars/rachel-thorne.jpg",
    reportedBy: "usr-demo-2",
    reportedByName: "Sarah Chen",
    reportedByAvatar: "/avatars/sarah-chen.jpg",
    resolvedAt: "2026-08-03T16:45:00Z",
    resolutionNotes: "Tuned stabilizationWindowSeconds to 300s and increased default minReplicas to 12.",
    createdAt: "2026-08-02T13:10:00Z",
    updatedAt: "2026-08-03T16:45:00Z",
  },
  {
    id: "iss-2026-018",
    title: "OAuth 2.0 PKCE challenge verification failure for mobile clients",
    description: "Base64URL encoding padding characters triggered 400 Bad Request on specific Android client versions.",
    category: IssueCategory.BUG,
    priority: IssuePriority.MEDIUM,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-7",
    assignedToName: "Liam O'Connor",
    assignedToAvatar: "/avatars/liam-oconnor.jpg",
    reportedBy: "usr-demo-3",
    reportedByName: "Marcus Vance",
    reportedByAvatar: "/avatars/marcus-vance.jpg",
    resolvedAt: "2026-07-22T14:30:00Z",
    resolutionNotes: "Stripped RFC 7636 padding chars in PKCE validator regex.",
    createdAt: "2026-07-21T10:00:00Z",
    updatedAt: "2026-07-22T14:30:00Z",
  },
  {
    id: "iss-2026-017",
    title: "Enterprise SSO SAML assertion signature validation cache miss",
    description: "IdP metadata cert refresh was querying remote endpoint on every assertion rather than leveraging Redis cache.",
    category: IssueCategory.SECURITY,
    priority: IssuePriority.HIGH,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-1",
    assignedToName: "Alex Morgan",
    assignedToAvatar: "/avatars/alex-morgan.jpg",
    reportedBy: "usr-demo-4",
    reportedByName: "Elena Rostova",
    reportedByAvatar: "/avatars/elena-rostova.jpg",
    resolvedAt: "2026-07-11T12:00:00Z",
    resolutionNotes: "Configured 24-hour Redis TTL on IdP SAML signing certificates with background re-fetch.",
    createdAt: "2026-07-10T15:20:00Z",
    updatedAt: "2026-07-11T12:00:00Z",
  },
  {
    id: "iss-2026-016",
    title: "GraphQL N+1 query vulnerability on team members query",
    description: "Fetching team list with 100 members executed 101 separate SQL queries for role permission lookups.",
    category: IssueCategory.PERFORMANCE,
    priority: IssuePriority.MEDIUM,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-2",
    assignedToName: "Sarah Chen",
    assignedToAvatar: "/avatars/sarah-chen.jpg",
    reportedBy: "usr-demo-5",
    reportedByName: "David Kim",
    reportedByAvatar: "/avatars/david-kim.jpg",
    resolvedAt: "2026-06-25T17:15:00Z",
    resolutionNotes: "Implemented DataLoader batching for member role resolution.",
    createdAt: "2026-06-24T09:40:00Z",
    updatedAt: "2026-06-25T17:15:00Z",
  },
  {
    id: "iss-2026-015",
    title: "CSV export truncation on datasets exceeding 50,000 rows",
    description: "Node.js response buffer reached memory ceiling on huge table export causing truncated download stream.",
    category: IssueCategory.BUG,
    priority: IssuePriority.MEDIUM,
    status: IssueStatus.CLOSED,
    assignedTo: "usr-demo-7",
    assignedToName: "Liam O'Connor",
    assignedToAvatar: "/avatars/liam-oconnor.jpg",
    reportedBy: "usr-demo-8",
    reportedByName: "Priya Patel",
    reportedByAvatar: "/avatars/priya-patel.jpg",
    resolvedAt: "2026-06-14T11:00:00Z",
    resolutionNotes: "Converted CSV generation to chunked HTTP streaming response with backpressure.",
    createdAt: "2026-06-13T14:15:00Z",
    updatedAt: "2026-06-14T11:00:00Z",
  },
  {
    id: "iss-2026-014",
    title: "AI Model inference queue deadlocks during simultaneous fine-tuning jobs",
    description: "Distributed lock on GPU node cluster failed to release when Celery worker caught SIGTERM.",
    category: IssueCategory.PERFORMANCE,
    priority: IssuePriority.CRITICAL,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-6",
    assignedToName: "Rachel Thorne",
    assignedToAvatar: "/avatars/rachel-thorne.jpg",
    reportedBy: "usr-demo-1",
    reportedByName: "Alex Morgan",
    reportedByAvatar: "/avatars/alex-morgan.jpg",
    resolvedAt: "2026-05-28T16:00:00Z",
    resolutionNotes: "Added Redis Redlock expiry TTL of 120 seconds with auto-renewal heartbeat.",
    createdAt: "2026-05-27T11:30:00Z",
    updatedAt: "2026-05-28T16:00:00Z",
  },
  {
    id: "iss-2026-013",
    title: "Database connection pool exhaustion during scheduled billing run",
    description: "PgBouncer reached max client connections (500) at 00:00 UTC due to non-pooled transaction hooks.",
    category: IssueCategory.DATABASE,
    priority: IssuePriority.HIGH,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-1",
    assignedToName: "Alex Morgan",
    assignedToAvatar: "/avatars/alex-morgan.jpg",
    reportedBy: "usr-demo-2",
    reportedByName: "Sarah Chen",
    reportedByAvatar: "/avatars/sarah-chen.jpg",
    resolvedAt: "2026-05-18T13:40:00Z",
    resolutionNotes: "Migrated billing reconciliation worker to dedicated transaction pooler port with 10s idle timeout.",
    createdAt: "2026-05-17T02:00:00Z",
    updatedAt: "2026-05-18T13:40:00Z",
  },
  {
    id: "iss-2026-012",
    title: "Multi-tenant workspace sub-domain SSL cert renewal failure via Let's Encrypt",
    description: "ACME challenge DNS validation rate limit triggered for newly provisioned customer custom domains.",
    category: IssueCategory.SECURITY,
    priority: IssuePriority.HIGH,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-6",
    assignedToName: "Rachel Thorne",
    assignedToAvatar: "/avatars/rachel-thorne.jpg",
    reportedBy: "usr-demo-4",
    reportedByName: "Elena Rostova",
    reportedByAvatar: "/avatars/elena-rostova.jpg",
    resolvedAt: "2026-04-26T15:30:00Z",
    resolutionNotes: "Integrated Cloudflare SSL for SaaS wildcard fallback provider.",
    createdAt: "2026-04-25T10:15:00Z",
    updatedAt: "2026-04-26T15:30:00Z",
  },
  {
    id: "iss-2026-011",
    title: "Search index desynchronization for projects modified via API keys",
    description: "Elasticsearch index update event was skipped when projects were modified using programmatic bearer tokens.",
    category: IssueCategory.BUG,
    priority: IssuePriority.MEDIUM,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-2",
    assignedToName: "Sarah Chen",
    assignedToAvatar: "/avatars/sarah-chen.jpg",
    reportedBy: "usr-demo-5",
    reportedByName: "David Kim",
    reportedByAvatar: "/avatars/david-kim.jpg",
    resolvedAt: "2026-04-12T17:00:00Z",
    resolutionNotes: "Moved indexing hooks from controller layer into database trigger event bus.",
    createdAt: "2026-04-11T13:50:00Z",
    updatedAt: "2026-04-12T17:00:00Z",
  },
  {
    id: "iss-2026-010",
    title: "Audit log table storage size growing exponentially without pruning partition",
    description: "Audit log table reached 45GB. Queries on recent records degraded from 40ms to 920ms.",
    category: IssueCategory.DATABASE,
    priority: IssuePriority.MEDIUM,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-1",
    assignedToName: "Alex Morgan",
    assignedToAvatar: "/avatars/alex-morgan.jpg",
    reportedBy: "usr-demo-6",
    reportedByName: "Rachel Thorne",
    reportedByAvatar: "/avatars/rachel-thorne.jpg",
    resolvedAt: "2026-03-24T18:30:00Z",
    resolutionNotes: "Implemented monthly table range partitioning and automated S3 cold storage offloading.",
    createdAt: "2026-03-23T11:00:00Z",
    updatedAt: "2026-03-24T18:30:00Z",
  },
  {
    id: "iss-2026-009",
    title: "Content Security Policy (CSP) violation on external analytics script",
    description: "Updated browser CSP rules blocked telemetry ping from third-party vendor tag manager.",
    category: IssueCategory.SECURITY,
    priority: IssuePriority.LOW,
    status: IssueStatus.CLOSED,
    assignedTo: "usr-demo-7",
    assignedToName: "Liam O'Connor",
    assignedToAvatar: "/avatars/liam-oconnor.jpg",
    reportedBy: "usr-demo-3",
    reportedByName: "Marcus Vance",
    reportedByAvatar: "/avatars/marcus-vance.jpg",
    resolvedAt: "2026-03-08T14:15:00Z",
    resolutionNotes: "Added sha256 hash nonce to Next.js middleware CSP header generation.",
    createdAt: "2026-03-07T16:40:00Z",
    updatedAt: "2026-03-08T14:15:00Z",
  },
  {
    id: "iss-2026-008",
    title: "Redis cluster failover caused 12-second payment state desync",
    description: "Sentinel failover elected new master while in-flight charge token was held in ephemeral memory.",
    category: IssueCategory.DEPLOYMENT,
    priority: IssuePriority.HIGH,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-6",
    assignedToName: "Rachel Thorne",
    assignedToAvatar: "/avatars/rachel-thorne.jpg",
    reportedBy: "usr-demo-1",
    reportedByName: "Alex Morgan",
    reportedByAvatar: "/avatars/alex-morgan.jpg",
    resolvedAt: "2026-02-22T19:00:00Z",
    resolutionNotes: "Configured WAIT command on critical payment state writes to ensure synchronous replica ACK.",
    createdAt: "2026-02-21T21:10:00Z",
    updatedAt: "2026-02-22T19:00:00Z",
  },
  {
    id: "iss-2026-007",
    title: "File upload chunk assembly failure on unstable mobile network connections",
    description: "Multipart upload resume failed when client IP address altered between cellular tower transitions.",
    category: IssueCategory.API,
    priority: IssuePriority.MEDIUM,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-2",
    assignedToName: "Sarah Chen",
    assignedToAvatar: "/avatars/sarah-chen.jpg",
    reportedBy: "usr-demo-4",
    reportedByName: "Elena Rostova",
    reportedByAvatar: "/avatars/elena-rostova.jpg",
    resolvedAt: "2026-02-12T16:20:00Z",
    resolutionNotes: "Signed upload URLs with session tokens rather than binding to client IP address.",
    createdAt: "2026-02-11T12:00:00Z",
    updatedAt: "2026-02-12T16:20:00Z",
  },
  {
    id: "iss-2026-006",
    title: "International currency formatting rounding error in multi-currency checkout",
    description: "Japanese Yen (JPY) was displaying 2 decimal places causing banking processor rejection.",
    category: IssueCategory.BUG,
    priority: IssuePriority.HIGH,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-7",
    assignedToName: "Liam O'Connor",
    assignedToAvatar: "/avatars/liam-oconnor.jpg",
    reportedBy: "usr-demo-5",
    reportedByName: "David Kim",
    reportedByAvatar: "/avatars/david-kim.jpg",
    resolvedAt: "2026-01-26T15:00:00Z",
    resolutionNotes: "Enforced ISO 4217 zero-decimal rules for JPY, KRW, and CLF across billing engine.",
    createdAt: "2026-01-25T10:30:00Z",
    updatedAt: "2026-01-26T15:00:00Z",
  },
  {
    id: "iss-2026-005",
    title: "Next.js SSR hydration error on dynamic time-ago timestamps",
    description: "Mismatch between server render time and client hydration on relative date badges.",
    category: IssueCategory.UI_UX,
    priority: IssuePriority.LOW,
    status: IssueStatus.CLOSED,
    assignedTo: "usr-demo-2",
    assignedToName: "Sarah Chen",
    assignedToAvatar: "/avatars/sarah-chen.jpg",
    reportedBy: "usr-demo-3",
    reportedByName: "Marcus Vance",
    reportedByAvatar: "/avatars/marcus-vance.jpg",
    resolvedAt: "2026-01-15T11:30:00Z",
    resolutionNotes: "Wrapped relative time formatter with suppressHydrationWarning and client-side mount hook.",
    createdAt: "2026-01-14T14:45:00Z",
    updatedAt: "2026-01-15T11:30:00Z",
  },
  {
    id: "iss-2025-004",
    title: "API rate limiting threshold too strict for high-volume enterprise webhooks",
    description: "Enterprise tier clients processing batch events were receiving 429 Too Many Requests.",
    category: IssueCategory.API,
    priority: IssuePriority.HIGH,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-1",
    assignedToName: "Alex Morgan",
    assignedToAvatar: "/avatars/alex-morgan.jpg",
    reportedBy: "usr-demo-6",
    reportedByName: "Rachel Thorne",
    reportedByAvatar: "/avatars/rachel-thorne.jpg",
    resolvedAt: "2025-12-20T17:00:00Z",
    resolutionNotes: "Increased token bucket capacity for Enterprise tier from 1,000 to 10,000 req/min.",
    createdAt: "2025-12-19T09:10:00Z",
    updatedAt: "2025-12-20T17:00:00Z",
  },
  {
    id: "iss-2025-003",
    title: "Deadlock in user session invalidation during bulk team member deactivation",
    description: "Database row locking order inconsistency during simultaneous admin staff operations.",
    category: IssueCategory.DATABASE,
    priority: IssuePriority.HIGH,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-1",
    assignedToName: "Alex Morgan",
    assignedToAvatar: "/avatars/alex-morgan.jpg",
    reportedBy: "usr-demo-2",
    reportedByName: "Sarah Chen",
    reportedByAvatar: "/avatars/sarah-chen.jpg",
    resolvedAt: "2025-12-08T18:00:00Z",
    resolutionNotes: "Ordered entity IDs before acquiring SELECT FOR UPDATE locks in transactional batch.",
    createdAt: "2025-12-07T15:20:00Z",
    updatedAt: "2025-12-08T18:00:00Z",
  },
  {
    id: "iss-2025-002",
    title: "AWS S3 presigned URL signature expiry during multi-gigabyte asset uploads",
    description: "Default 15-minute presigned expiry was insufficient for customer backup archive uploads.",
    category: IssueCategory.API,
    priority: IssuePriority.MEDIUM,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-6",
    assignedToName: "Rachel Thorne",
    assignedToAvatar: "/avatars/rachel-thorne.jpg",
    reportedBy: "usr-demo-4",
    reportedByName: "Elena Rostova",
    reportedByAvatar: "/avatars/elena-rostova.jpg",
    resolvedAt: "2025-11-18T14:30:00Z",
    resolutionNotes: "Implemented dynamic expiry calculation based on reported file size and minimum bandwidth.",
    createdAt: "2025-11-17T11:00:00Z",
    updatedAt: "2025-11-18T14:30:00Z",
  },
  {
    id: "iss-2025-001",
    title: "Nginx reverse proxy buffer overflow on large JSON response payloads",
    description: "Nginx proxy_buffers default (4 4k) caused temporary disk buffering and 80ms latency penalty.",
    category: IssueCategory.DEPLOYMENT,
    priority: IssuePriority.MEDIUM,
    status: IssueStatus.RESOLVED,
    assignedTo: "usr-demo-1",
    assignedToName: "Alex Morgan",
    assignedToAvatar: "/avatars/alex-morgan.jpg",
    reportedBy: "usr-demo-6",
    reportedByName: "Rachel Thorne",
    reportedByAvatar: "/avatars/rachel-thorne.jpg",
    resolvedAt: "2025-10-20T16:00:00Z",
    resolutionNotes: "Tuned proxy_buffers to 16 64k and proxy_buffer_size to 128k.",
    createdAt: "2025-10-19T13:40:00Z",
    updatedAt: "2025-10-20T16:00:00Z",
  },
]

// Mutable in-memory stores for runtime persistence during client demo
const demoContentReports: ContentReport[] = [...INITIAL_DEMO_CONTENT_REPORTS]
const demoSystemIssues: SystemIssue[] = [...INITIAL_DEMO_SYSTEM_ISSUES]

export function getDemoContentReports(): ContentReport[] {
  return [...demoContentReports]
}

export function getDemoContentReportsStats(): ContentReportStats {
  const total = demoContentReports.length
  const pending = demoContentReports.filter((r) => r.status === ReportStatus.PENDING).length
  const reviewing = demoContentReports.filter((r) => r.status === ReportStatus.REVIEWING).length
  const resolved = demoContentReports.filter((r) => r.status === ReportStatus.RESOLVED).length
  const dismissed = demoContentReports.filter((r) => r.status === ReportStatus.DISMISSED).length

  return { total, pending, reviewing, resolved, dismissed }
}

export function updateDemoContentReportStatus(
  reportId: string,
  status: ReportStatus,
  resolutionNotes?: string,
  actionTaken?: string
): ContentReport {
  const index = demoContentReports.findIndex((r) => r.id === reportId)
  const existing = demoContentReports[index]
  if (index === -1 || !existing) {
    throw new Error(`Report with id ${reportId} not found`)
  }

  const updated: ContentReport = {
    ...existing,
    status,
    resolutionNotes: resolutionNotes ?? existing.resolutionNotes,
    actionTaken: actionTaken ?? existing.actionTaken,
    resolvedAt: status === ReportStatus.RESOLVED ? new Date().toISOString() : existing.resolvedAt,
    resolvedBy: status === ReportStatus.RESOLVED ? "Alex Morgan" : existing.resolvedBy,
    updatedAt: new Date().toISOString(),
  }

  demoContentReports[index] = updated
  return updated
}

export function getDemoSystemIssues(): SystemIssue[] {
  return [...demoSystemIssues]
}

export function getDemoSystemIssuesStats(): SystemIssueStats {
  const total = demoSystemIssues.length
  const open = demoSystemIssues.filter((i) => i.status === IssueStatus.OPEN).length
  const inProgress = demoSystemIssues.filter((i) => i.status === IssueStatus.IN_PROGRESS).length
  const resolved = demoSystemIssues.filter((i) => i.status === IssueStatus.RESOLVED).length
  const closed = demoSystemIssues.filter((i) => i.status === IssueStatus.CLOSED).length

  return { total, open, inProgress, resolved, closed }
}

export function updateDemoSystemIssueStatus(
  issueId: string,
  status: IssueStatus,
  resolutionNotes?: string
): SystemIssue {
  const index = demoSystemIssues.findIndex((i) => i.id === issueId)
  const existing = demoSystemIssues[index]
  if (index === -1 || !existing) {
    throw new Error(`System issue with id ${issueId} not found`)
  }

  const updated: SystemIssue = {
    ...existing,
    status,
    resolutionNotes: resolutionNotes ?? existing.resolutionNotes,
    resolvedAt: status === IssueStatus.RESOLVED ? new Date().toISOString() : existing.resolvedAt,
    updatedAt: new Date().toISOString(),
  }

  demoSystemIssues[index] = updated
  return updated
}
